name = "c360-web"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "apps/web"
watch_paths = ["apps/web/src"]

[build.upload]
format = "modules"
main = "./dist/index.js"

[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_NAMESPACE_ID"

[env.staging]
name = "c360-web-staging"

[env.production]
name = "c360-web-prod"
routes = [
  { pattern = "compliance.yourdomain.com", custom_domain = true }
]